name: Build and Deploy
on:
  repository_dispatch:
jobs:
  build:
    # build should only happen if client_payload.tenant is not null and in ['hsf', 'tgs']
    # build should only happen if client_payload.env is not null and in ['master', 'staging', 'uat', 'prod']
    if: github.event.client_payload.tenant == 'hsf' || github.event.client_payload.tenant == 'tgs' || github.event.client_payload.env == 'master' || github.event.client_payload.env == 'staging'|| github.event.client_payload.env == 'uat' || github.event.client_payload.env == 'prod'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Tenant
        run: |
          echo ::set-output name=action_tenant::${{ github.event.client_payload.tenant }}
        id: tenant
      - name: Set Environment
        run: echo ::set-output name=action_env::${{ github.event.client_payload.env }}
        id: env
      - name: Yarn Install with cache
        uses: bahmutov/npm-install@v1
      - name: Build project
        run: |
          echo GATSBY_TENANT=${{ github.event.client_payload.tenant }} >> .env.hsf.master
          echo CMS_URL=${{  secrets.HSF_DEV_CMS_URL }} >> .env.hsf.master
          echo CMS_PROJECT_NAME=${{ secrets.HSF_DEV_CMS_PROJECT_NAME }} >> .env.hsf.master
          echo CMS_PROJECT_NAME=${{ secrets.HSF_DEV_CMS_USERNAME }} >> .env.hsf.master
          echo CMS_PASSWORD=${{ secrets.HSF_DEV_CMS_PASSWORD }} >> .env.hsf.master
          yarn install
          yarn build
        env:
          CI: true
          GATSBY_ACTIVE_TENANT: ${{ steps.tenant.outputs.action_tenant }} # should come from client_payload.tenant
          GATSBY_ACTIVE_ENV: ${{ steps.env.outputs.action_env }} # same as above
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public
      # Deploy artifacts to Amazon S3 Bucket
      - name: Deploy artifacts to Amazon S3 Bucket
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 public s3://cms-gatsby --no-progress --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
